config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  
  post "welcome/login_attempt" => "welcome#login_attempt"
  resources :mentors
  get "mentors/detail/:id" => "mentors#detail", as: :mentors_detail

  get "welcome/forget_password" => "welcome#forget_password"
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get "administrators/new" => "administrators#new"
  get "administrators/create/:id" => "administrators#create", as: :administrators_create
  get "administrators/index" => "administrators#index"
  get "administrators/delete_one/:id" => "administrators#delete_one", as: :administrators_delete_one
  get "administrators/drop_table" => "administrators#drop_table"
  get "administrators/drop_all_mentor" => "administrators#drop_all_mentor"
  get "welcome/faq_open" => "welcome#faq_open"
  
  get "welcome/index" => "welcome#index"
  get "welcome/parent_signin" => "welcome#parent_signin"
  get "welcome/logout" => "welcome#logout"
  get "mentors_new" => "mentors#new"
  get "groupinvs/send_inv/:id" => "groupinvs#send_inv", as: :groupinvs_send_inv
  get "groupinvs/accept_inv_mentor/:id" => "groupinvs#accept_inv_mentor", as: :groupinvs_accept_inv_mentor
  get "groupinvs/accept_inv_group/:id" => "groupinvs#accept_inv_group", as: :groupinvs_accept_inv_group
  get "groupinvs/cancel_inv/:id" => "groupinvs#cancel_inv", as: :groupinvs_cancel_inv
  get "groupinvs/decline_inv/:id" => "groupinvs#decline_inv", as: :groupinvs_decline_inv
  
  get "parent" => "parent#index"
  get "parent/edit" => "parent#edit"
  put "parent" => "parent#update"
  get "parent/new" => "parent#new"
  post "parent/create" => "parent#create"
  
  get "mentor/quit_group/:id" => "mentors#quit_group", as: :mentor_quit_group
  get "invitation/group_send_inv_to_child/:id" =>"invitation#group_send_inv_to_child", as: :invitation_group_send_inv_to_child
  get "invitation/child_accept_group/:id" =>"invitation#child_accept_group", as: :invitation_child_accept_group
  get "invitation/cancel_inv/:id" => "invitation#cancel_inv", as: :invitation_cancel_inv
  get "invitation/decline_inv/:id" => "invitation#decline_inv", as: :invitation_decline_inv
  get "invitation/child_send_request_to_group/:id" => "invitation#child_send_request_to_group", as: :invitation_child_send_request_to_group
  
  get "invitation/group_accept_child/:id" => "invitation#group_accept_child", as: :invitation_group_accept_child
  resources :user
  resources :rglusers
  get 'fbuser/fb_login' => 'fbuser#fb_login', as: :fb_auth
  get 'casusers/cas_login' => 'casusers#cas_login', as: :cas_login
  get 'casusers/cas_logout' => 'casusers#cas_logout', as: :cas_logout
  resources :child
  get "child/detail/:id" => "child#detail", as: :child_detail
  get "child/message/:id" => "child#message", as: :child_message
  get "child/quit_group/:id" => "child#quit_group", as: :child_quit_group
  
  
  resources :group do
    collection do
      get 'index_for_parent'
    end
  end
    
  get 'group/:id/change' => 'group#change', as: :change_group
  get "group/set_complete/:id" => "group#set_complete", as: :group_set_complete
  get "group/set_need_mentor/:id" => "group#set_need_mentor", as: :group_set_need_mentor
  get "group/detail/:id" => "group#detail", as: :group_detail
  get "group/message/:id" => "group#message", as: :group_message
  root 'welcome#index'

end

app/models/child.rb
class Child < ActiveRecord::Base
    belongs_to :parent
    belongs_to :group
    has_many :sent_invitations, class_name: "Invitation", as: :sender
    has_many :relsceived_invitations, class_name: "Invitation", as: :receiver

    def name
        self.firstname+' '+self.lastname
    end
    
    def age 
        dob = self.date_of_birth
        now = Time.now.utc.to_date
        age_year = now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
        if dob.month < now.month
            age_month = now.month - dob.month
        elsif dob.month > now.month
            age_month = now.month + 12 - dob.month
        else
            age_month = 0
        end
        if age_month == 0
            return age_year.to_s + ' years'
        elsif age_month == 1
            return age_year.to_s + ' years and ' + age_month.to_s + ' month'
        else
            return age_year.to_s + ' years and ' + age_month.to_s + ' months'
        end
    end
    
    validates :firstname, :presence => true
    validates :lastname, :presence => true
    validates :gender, :presence => true
    validates :school, :presence => true
    validates :grade, :presence => true
    validates :date_of_birth, :presence => true
    validate :is_valid_dob?
    validates :time_slot, :presence => true
    validates :description, :length => { :in => 0..301}
    
    private 
      def is_valid_dob?
          errors.add(:dob, "Invalid date of birth") unless !date_of_birth.nil? && date_of_birth.past?
      end
end

app/controllers/child_controller.rb
class ChildController < ApplicationController
    def index
        @user = User.whois(session)
        redirect_to root_path and return if @user.nil?
        if !session[:group_id].nil?
            
            @group = Group.find_by_id(session[:group_id])
        else
            flash[:warning] = "Invalid user!"
            reset_session
            redirect_to welcome_index_path and return
        end
        
        if !@user.nil? && @user.role == "Parent"
            case params[:sort]
            when 'age'
                @children=Child.where(:visible => true, :group_id => nil).order(date_of_birth: :desc)
            when 'time'
                @children=Child.where(:visible => true, :group_id => nil).sort_by{|c| @group.time_compare(c.time_slot)}.reverse
            else
                @children = Child.where(:visible => true, :group_id => nil)
            end
        else
            flash[:warning] = "Invalid user!"
            session[:user_id] = nil
            redirect_to welcome_index_path and return
        end
    end
    
    def show
        @user=User.whois(session)
        redirect_to root_path and return if @user.nil?
        #rinv = Invitation.where(:sender_id => params[:id], :receiver_id => @user.parent.children)
        
        @child = Child.find_by_id(params[:id])
        #if (@child.nil? || (rinv.empty? && @child.parent.user_id != @user.id))
            #flash[:warning] = "Sorry, your user account is not allowed to access this information."
            #redirect_to parent_path and return
        #end
        @mychild = @child.parent.user_id == @user.id
    end
    
    def detail
        @user=User.whois(session)
        redirect_to root_path and return if @user.nil?
        @child = Child.find_by_id(params[:id])
        @mychild = @child.parent.user_id == @user.id
        if @user.role == 'Parent'
            @group = Group.find_by_id(params[:group_id])
            @time_slot = [@child.time_slot, @group.time_slot].join(',')
        else
            @time_slot = @child.time_slot
        end
    end
    
    def message
        @user = User.whois(session)
        redirect_to root_path and return if @user.nil?
        @child = Child.find_by_id(params[:id])
        if (@child.nil? ||  @child.parent.user_id != @user.id)
            flash[:warning] = "Sorry, your user account is not allowed to access this information."
            redirect_to parent_path and return
        end
        @rinv=Invitation.where(:receiver_id => @child).where(:sender_id => nil)
        @srequest = Invitation.where(:sender_id => @child).where(:receiver_id => nil)
    end
    
    
    def edit
        @user=User.whois(session)
        redirect_to root_path and return if @user.nil?
        @child = Child.find_by_id(params[:id])
        if (@child.nil? ||  @child.parent.user_id != @user.id)
            flash[:warning] = "Sorry, your user account is not allowed to access this information."
            redirect_to parent_path and return
        end
    end
    
    def update
        @user=User.whois(session)
        redirect_to root_path and return if @user.nil?
        @child = Child.find_by_id(params[:id])
        if (@child.nil? ||  @child.parent.user_id != @user.id)
            flash[:warning] = "Sorry, your user account is not allowed to access this information."
            redirect_to parent_path and return
        end
        if @child.update_attributes(child_params)
            flash[:success] = "Your child Information has been updated successfully"
            redirect_to child_path(@child.id) and return
        else
            flash[:danger] = "The information you put is invalid"
            redirect_to edit_child_path(@child) and return
        end
    end
    
    def new
        @user=User.whois(session)
        redirect_to root_path and return if @user.nil?
        @child=Child.new
    end
    
    def create
        @user=User.whois(session)
        redirect_to root_path and return if @user.nil?
        @child=Child.new(child_params)
        @child.parent_id = @user.parent.id
        if @child.save
            flash[:success] = "Your child has been created successfully"
            redirect_to parent_path and return
        else
            flash[:danger] = "The information you put is invalid"
            redirect_to new_child_path and return
        end
    end
        
    
    def destroy
        @user=User.whois(session)
        redirect_to root_path and return if @user.nil?
        @child=Child.find_by_id(params[:id])
        if @child.group.nil?
            @rinv = Invitation.where(:receiver => @child, :status => 'Pending')
            @rinv.each do |ri|
                ri.status = "Declined"
                ri.save!
            end
            @srequest = Invitation.where(:sender => @child, :status => 'Pending')
            @srequest.each do |sr|
                sr.destroy
            end
            @child.destroy
            
            redirect_to parent_path
            flash[:success]="You have deleted a child successfully!"
        else
            redirect_to parent_path
            flash[:warning]="Your child cannot be deleted before quitting the group!"
        end
    end
    
    def quit_group
        
        @child = Child.find_by_id(params[:id])
        GroupMailer.child_quit_request(@child).deliver_now
        redirect_to parent_path
        flash[:success] = "An email has been sent to the coach"
    end
    
    
    private
    
    def child_params
        params.require(:child).permit(:firstname, :lastname, :gender, :date_of_birth, :school, :grade, :time_slot, :competitions, :description, :visible)
    end
end

app/helpers/child_helper.rb
module ChildHelper
end

app/views/child/detail.html.erb
<div class='row'>
  <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
    <h1 align="center" class="animated fadeInDown" style=color:#339900>Child Profile</h1>
    <br>
    <br>
    <div class='col-sm-12'>
      <div class="table-responsive">
        <table class='table'>
          <tbody>
            <tr>
              <td>ID</td>
              <td><%= @child.id %></td>
            </tr>
            <tr>
              <td>Gender</td>
              <td><i class='fa fa-<%= @child.gender.downcase %>'></i></td>
            </tr>
            <tr>
              <td>Age</td>
              <td><%= @child.age %></td>
            </tr>
            <tr>
              <td>School</td>
              <td><%= @child.school %></td>
            </tr>
            <tr>
              <td>Grade</td>
              <td><%= @child.grade %></td>
            </tr>
            <tr>
              <td>Competition</td>
              <td><%= @child.competitions %></td>
            </tr>
            <tr>
              <td>Description</td>
              <td><%= @child.description %></td>
            </tr>
            <% if @mychild %>
              <tr>
                <td>Visible</td>
                <td><i class='fa fa-eye<%= "-slash" if !@child.visible %>'></i></td>
              </tr>
            <% else %>
              <tr>
                <td>Parent</td>
                <td><%= @child.parent.name %></td>
              </tr>
              <tr>
                <td>Phone</td>
                <td><%= @child.parent.phone %></td>
              </tr>
              <tr>
                <td>Email</td>
                <td><%= @child.parent.email %></td>
              </tr>
            <% end %>
            <% if @child.group.nil? %>
              <tr>
                <td>Group</td>
                <td></td>
              </tr>
              <tr>
                <td>Mentor</td>
                <td></td>
              </tr>
            <% else %>
              <tr>
                <td>Group</td>
                <td><%= @child.group.title %></td>
              </tr>
              <tr>
                <td>Mentor</td>
                <% if @child.group.mentor.nil? %>
                  <td></td>
                <% else %>
                  <td><%= @child.group.mentor.name %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class='time-board time-board-hover' value = '<%=@time_slot%>' ></div>
      <hr>
      <%#= link_to "Back", child_index_path , :class => 'btn btn-block btn-default'%>
    </div>
  </div>
</div>

app/views/child/edit.html.erb
<div class='row'>
  <div class="col-sm-12">
    <h1 align="center" class="animated fadeInDown" style=color:#339900>Edit Child Profile</h1>
    <br/>
    <div class="Sign_Form">
      <%= form_for @child, :method => :put ,:html => {:class => "form-horizontal"} do |f| %>
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
          <div class="form-group">
            <label class="control-label">All fields are required unless marked as 'Optional'</label>
          </div>
          <div class="form-group">
            <label for="inputFirstname" class="control-label edit-font">Firstname</label>
            <%= f.text_field :firstname, :class => 'form-control'%>
          </div>
          <div class="form-group">
            <label for="inputLastname" class="control-label edit-font">Lastname</label>
            <%= f.text_field :lastname, :class => 'form-control'%>
          </div>
          <div class="form-group">
            <label for="inputGender" class="control-label edit-font">Gender</label>
            <%= f.select(:gender, ['Male' , 'Female'], {},{:class => 'form-control'})%>
          </div>
          <div class="form-group">
            <label for="inputDOB" class="control-label edit-font">Date of Birth</label>
            <%= f.date_field :date_of_birth, :class => 'form-control'%>
          </div>
          <div class="form-group">
            <label for="inputSchool" class="control-label edit-font">School:</label>
            <%= f.text_field :school , :class => 'form-control' %>
          </div>
          <div class="form-group">
            <label for="inputGrade" class="control-label edit-font">Grade:</label>
            <%= f.text_field :grade , :class => 'form-control' %>
          </div>
          <div class="form-group">
            <label for="inputCompetitions" class="control-label edit-font">Competitions</label>
            <br/>
            <label class="radio-inline"><%= f.radio_button :competitions, 'FLL'%> FIRST LEGO League</label>
            <label class="radio-inline"><%= f.radio_button :competitions, 'Junior FLL'%> FIRST LEGO League Jr.</label>
          </div>
          <div class="form-group">
            <label for="inputVisibility" class="control-label">Visibility:</label>
            <br/>
            <div class="checkbox">
              <label class="checkbox-inline">
                <%= f.check_box :visible , :checked => (@child.visible)%> Visible
            </label>
            </div>
          </div>
          <div class="form-group">
            <label for="inputDescription" class="control-label edit-font">Description(Optional):</label>
            <%= f.text_area :description, :class => 'form-control'%>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
          <div class="form-group">
            <label for="inputTimeslot" class="control-label edit-font">Time Available</label>
            <br/>
            <div class='time-board time-board-input time-board-hover' value='<%= @child.time_slot %>' inputname='child[time_slot]'></div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
          <div class="form-group">
            <br/>
            <br/>
            <%= f.submit "UPDATE",:class => 'btn btn-block btn-success'%>
            <%= link_to "CANCEL",child_path(@child),:class => 'btn btn-block btn-default'%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/child/index.html.erb
<div class='row'>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <h1>Children List</h1>
    <div class="table-responsive">
      <table class='table'>
        <thead>
          <tr>
            <th><%= link_to 'ID', child_index_path(sort: 'id') %></th>
            <th>Gender</th>
            <th><%= link_to 'Age', child_index_path(sort: 'age')%></th>
            <th>School</th>
            <th>Grade</th>
            <th>Competition</th>
            <th><%= link_to 'Available Time', child_index_path(sort: 'time')%></th>
            <th>More</th>
          </tr>
        </thead>
        <tbody>
          <% @children.each do |child| %>
            <tr>
              <td><%= link_to child.id, child_detail_path(:id => child.id, :group_id => @group.id) %></td>
              <td><i class="fa fa-<%= child.gender.downcase %>"></i></td>
              <td><%= child.age %></td>
              <td><%= child.school %></td>
              <td><%= child.grade %></td>
              <td><%= child.competitions %></td>
              <td><%= @group.time_compare(child.time_slot) %>hrs</td>
              <td><%= link_to "Send invitation", {:controller => 'invitation', :action => 'group_send_inv_to_child', :id => @group.id, :rec_id => child.id}, data: {:confirm => 'Are you sure?'}  %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= link_to "Back", group_path(@group) %>

app/views/child/message.html.erb
<div class='row'>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <h2>Invitations to my child </h2>
    <% if @rinv.empty? %>
      <p align=center>None</p>
    <% else %>
      <div class="table-responsive">
        <table class='table'>
          <thead>
            <tr>
              <th>Group</th>
              <th>Competition</th>
              <th>Member</th>
              <th></th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <% @rinv.each do |inv| %>
              <tr>
                <td><%= link_to inv.group.title, group_detail_path(:id => inv.group.id, :child_id => @child.id) %></td>
                <td><%= inv.group.competitions %></td>
                <td><%= inv.group.members %></td>
                <td></td>
                <% if inv.status == "Pending"%>
                  <td><%= link_to "Accept", invitation_child_accept_group_path(inv) %> or <%= link_to "Decline", invitation_decline_inv_path(inv) %></td>
                <% else %>
                  <td><%= inv.status %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>
<div class='row'>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <h2>Sent Request from my child</h2>
    <% if @srequest.empty? %>
      <p align=center>None</p>
    <% else %>
      <div class="table-responsive">
        <table class='table'>
          <thead>
            <tr>
              <th>Group</th>
              <th>Competition</th>
              <th>Member</th>
              <th></th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <% @srequest.each do |r| %>
              <tr>
                <td><%= link_to r.group.title, group_detail_path(:id => r.group.id, :child_id => @child.id) %></td>
                <td><%= r.group.competitions %></td>
                <td><%= r.group.members %></td>
                <td></td>
                <% if r.status == "Pending"%>
                  <td><%= link_to "Cancel", invitation_cancel_inv_path(r) %></td>
                <% else %>
                  <td><%= r.status %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>
<%= link_to "Back", parent_path %>

app/views/child/new.html.erb
<div class='row'>
  <div class="col-sm-12">
    <h1 align="center" class="animated swing" style=color:#339900>Create Child Account</h1>
    <br/>
    <div class="Sign_Form">
      <%= form_for(:child, :url => {:controller => 'child', :action => 'create'}, :html => {:class => "form-horizontal"}) do |f| %>
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
          <div class="form-group">
            <label class="control-label">All fields are required unless marked as 'Optional'</label>
          </div>
          <div class="form-group">
            <%= f.text_field :firstname, :placeholder =>'Firstname',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.text_field :lastname, :placeholder =>'Lastname',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.select(:gender, ['Male' , 'Female'], {prompt:"Gender"},{:class => 'form-control'})%>
          </div>
          <div class="form-group">
            <%= f.date_field :date_of_birth, :placeholder =>'Date of Birth',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.text_field :school, :placeholder =>'School',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.text_field :grade, :placeholder =>'Grade',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <label for="inputCompetitions" class="control-label">Competitions:</label>
            <br/>
            <label class="radio-inline"><%= f.radio_button :competitions, 'FLL'%> FIRST LEGO League</label>
            <label class="radio-inline"><%= f.radio_button :competitions, 'Junior FLL'%> FIRST LEGO League Jr.</label>
          </div>
          <div class="form-group">
            <label for="inputVisibility" class="control-label">Visibility:</label>
            <br/>
            <div class="checkbox">
              <label class="checkbox-inline">
                <%= f.check_box :visible%> Other groups can see you
            </label>
            </div>
          </div>
          <div class="form-group">
            <label for="inputDescription" class="control-label">Description (Optional):</label>
            <br/>
            <%= f.text_area :description, :placeholder =>'More About Yourself',:class => 'form-control'%>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
          <div class="form-group">
            <label for="inputTimeslot" class="control-label">Time Available</label>
            <br/>
            <div class='time-board time-board-input time-board-hover' value='<%= @child.time_slot %>' inputname='child[time_slot]'></div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
          <div class="form-group">
            <%= f.submit "CREATE",:class => 'btn btn-block btn-success' %>
            <%= link_to "CANCEL", parent_path, :class =>'btn btn-block btn-default'%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% if @child.errors.any? %>
  <ul class="Signup_Errors">
    <% for message_error in @child.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
  </ul>
<% end %>
</div>
</div>

app/views/child/show.html.erb
<div class='row'>
  <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
    <h1 align="center" class="animated fadeInDown" style="color:#339900;">Child Profile</h1>
    <br>
    <br>
    <div class='col-sm-12'>
      <div class="table-responsive">
        <table class='table'>
          <tbody>
            <tr>
              <td>#</td>
              <td><%= @child.id %></td>
            </tr>
            <tr>
              <td>Name</td>
              <td><%= @child.name %></td>
            </tr>
            <tr>
              <td>Gender</td>
              <td><i class='fa fa-<%= @child.gender.downcase %>'></i></td>
            </tr>
            <tr>
              <td>Age</td>
              <td><%= @child.age %></td>
            </tr>
            <tr>
              <td>School</td>
              <td><%= @child.school %></td>
            </tr>
            <tr>
              <td>Grade</td>
              <td><%= @child.grade %></td>
            </tr>
            <tr>
              <td>Competition</td>
              <td><%= @child.competitions %></td>
            </tr>
            <tr>
              <td>Description</td>
              <td><%= @child.description %></td>
            </tr>
            <% if @mychild %>
              <tr>
                <td>Visible</td>
                <td><i class='fa fa-eye<%= "-slash" if !@child.visible %>'></i></td>
              </tr>
            <% else %>
              <tr>
                <td>Parent</td>
                <td><%= @child.parent.name %></td>
              </tr>
              <tr>
                <td>Phone</td>
                <td><%= @child.parent.phone %></td>
              </tr>
              <tr>
                <td>Email</td>
                <td><%= @child.parent.email %></td>
              </tr>
            <% end %>
            <% if @child.group.nil? %>
              <tr>
                <td>Group</td>
                <td></td>
              </tr>
              <tr>
                <td>Mentor</td>
                <td></td>
              </tr>
            <% else %>
              <tr>
                <td>Group</td>
                <td><%= @child.group.title %></td>
              </tr>
              <tr>
                <td>Mentor</td>
                <% if @child.group.mentor.nil? %>
                  <td></td>
                <% else %>
                  <td><%= @child.group.mentor.name %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class='time-board time-board-hover' value = '<%=@child.time_slot%>' ></div>
      <hr>
      <% if @mychild %>
        <%= link_to "Edit", edit_child_path(@child) , :class => 'btn btn-block btn-success'%>
        <%= link_to "Delete", child_path(@child), :class => 'btn btn-block btn-danger', data: {:confirm => 'Are you sure?'}, method: :delete %>
        <% if !@child.group.nil? %>
          <%= link_to "Quit this group", {:controller => "child", :action => "quit_group", :id => @child.id}, data: {:confirm => 'Are you sure?'}, :class => 'btn btn-block btn-danger' %><br/>
        <% end %>
      <% end %>
      <%= link_to "Back", parent_path , :class => 'btn btn-block btn-default'%>
    </div>
  </div>
</div>