config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  
  post "welcome/login_attempt" => "welcome#login_attempt"
  resources :mentors
  get "mentors/detail/:id" => "mentors#detail", as: :mentors_detail

  get "welcome/forget_password" => "welcome#forget_password"
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get "administrators/new" => "administrators#new"
  get "administrators/create/:id" => "administrators#create", as: :administrators_create
  get "administrators/index" => "administrators#index"
  get "administrators/delete_one/:id" => "administrators#delete_one", as: :administrators_delete_one
  get "administrators/drop_table" => "administrators#drop_table"
  get "administrators/drop_all_mentor" => "administrators#drop_all_mentor"
  get "welcome/faq_open" => "welcome#faq_open"
  
  get "welcome/index" => "welcome#index"
  get "welcome/parent_signin" => "welcome#parent_signin"
  get "welcome/logout" => "welcome#logout"
  get "mentors_new" => "mentors#new"
  get "groupinvs/send_inv/:id" => "groupinvs#send_inv", as: :groupinvs_send_inv
  get "groupinvs/accept_inv_mentor/:id" => "groupinvs#accept_inv_mentor", as: :groupinvs_accept_inv_mentor
  get "groupinvs/accept_inv_group/:id" => "groupinvs#accept_inv_group", as: :groupinvs_accept_inv_group
  get "groupinvs/cancel_inv/:id" => "groupinvs#cancel_inv", as: :groupinvs_cancel_inv
  get "groupinvs/decline_inv/:id" => "groupinvs#decline_inv", as: :groupinvs_decline_inv
  
  get "parent" => "parent#index"
  get "parent/edit" => "parent#edit"
  put "parent" => "parent#update"
  get "parent/new" => "parent#new"
  post "parent/create" => "parent#create"
  
  get "mentor/quit_group/:id" => "mentors#quit_group", as: :mentor_quit_group
  get "invitation/group_send_inv_to_child/:id" =>"invitation#group_send_inv_to_child", as: :invitation_group_send_inv_to_child
  get "invitation/child_accept_group/:id" =>"invitation#child_accept_group", as: :invitation_child_accept_group
  get "invitation/cancel_inv/:id" => "invitation#cancel_inv", as: :invitation_cancel_inv
  get "invitation/decline_inv/:id" => "invitation#decline_inv", as: :invitation_decline_inv
  get "invitation/child_send_request_to_group/:id" => "invitation#child_send_request_to_group", as: :invitation_child_send_request_to_group
  
  get "invitation/group_accept_child/:id" => "invitation#group_accept_child", as: :invitation_group_accept_child
  resources :user
  resources :rglusers
  get 'fbuser/fb_login' => 'fbuser#fb_login', as: :fb_auth
  get 'casusers/cas_login' => 'casusers#cas_login', as: :cas_login
  get 'casusers/cas_logout' => 'casusers#cas_logout', as: :cas_logout
  resources :child
  get "child/detail/:id" => "child#detail", as: :child_detail
  get "child/message/:id" => "child#message", as: :child_message
  get "child/quit_group/:id" => "child#quit_group", as: :child_quit_group
  
  
  resources :group do
    collection do
      get 'index_for_parent'
    end
  end
    
  get 'group/:id/change' => 'group#change', as: :change_group
  get "group/set_complete/:id" => "group#set_complete", as: :group_set_complete
  get "group/set_need_mentor/:id" => "group#set_need_mentor", as: :group_set_need_mentor
  get "group/detail/:id" => "group#detail", as: :group_detail
  get "group/message/:id" => "group#message", as: :group_message
  root 'welcome#index'

end

app/models/rgluser.rb
class Rgluser < ActiveRecord::Base
    belongs_to :user
    
    
    before_save :encrypt_password
    after_save :clear_password
    def encrypt_password
        if password.present?
        self.salt = BCrypt::Engine.generate_salt
        self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
        end
    end
    def clear_password
        self.password = nil
    end
    
    def self.authenticate(username="", login_password="")
        rgluser = Rgluser.find_by_username(username)
        if rgluser && rgluser.match_password(login_password)
            return rgluser
        else
            return false
        end
    end   
    def match_password(login_password="")
        encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
    end
    
    def send_password_reset_email
        ParentMailer.password_reset(self).deliver_now
    end
    
    def password_reset_expired?
      reset_sent_at < 2.hours.ago
    end
    
    def create_reset_digest
        self.reset_token = Rgluser.new_token
        update_attribute(:reset_digest,  Rgluser.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end
    
    def name
        if self.user.role == "Parent"
            return self.user.parent.name if !self.user.parent.nil?
        else
            return self.user.mentor.name if !self.user.mentor.nil?
        end
        return "new user"
    end
    
    def firstname
        if self.user.role == 'Parent'
            return self.user.parent.firstname if !self.parent.nil?
        else
            return self.user.mentor.firstname if !self.mentor.nil?
        end
        return "new user"
    end
    

    
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    validates :password, :confirmation => true #password_confirmation attr
    validates_length_of :password, :in => 6..20, :on => :create
    
    private
    
    def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end
    
    def self.new_token
      SecureRandom.urlsafe_base64
    end
    
end

app/controllers/rglusers_controller.rb
class RglusersController < ApplicationController  

  
  def new
  end
  
  def create
    @user = User.new
    @user.role='Parent'
    @user.last_login_time = Time.zone.now
    @user.save
    session[:user_id] = @user.id
    session[:expires_at] = Time.current + 2.hours
    @rgluser = Rgluser.new(rgluser_params)
    @rgluser.user_id=@user.id
    @rgluser.role='Parent'
    if @rgluser.save
      flash[:success] = "You signed up successfully"
      @user.username = @rgluser.username
      @user.save
      redirect_to parent_new_path and return
    else
      flash[:warning] = "Form is invalid"
      redirect_to new_rgluser_path and return
    end
  end

  
  def edit
  end
  def update
  end
  def destroy
  end
  def show
  end
  def index
  end
  
  private
  
  def rgluser_params
    params.require(:rgluser).permit(:username, :password, :encrypted_password, :salt, :password_confirmation, :last_login_time)
  end
end

app/helpers/rglusers_helper.rb
module RglusersHelper
end

app/views/rglusers/new.html.erb
<!--<% @page_title = "UserAuth | Signup" %>-->
<div class='row'>
  <div class="col-xs-12 col-sm-8 col-md-6 col-lg-4 col-sm-offset-2 col-md-offset-3 col-lg-offset-4">
    <div class="parent-login", style="padding-top:15%;">
      <div class="list-inline">
        <%= link_to '<i class="fa fa-facebook fa-fw"></i><span class="network-name"> Sign up with facebook</span>'.html_safe, "/auth/facebook", id: "sign_in" , :class => 'btn btn-default btn-block', :style => "background-color:#3B5998;color:white;border-color:#2B4988;" %>
        <div style="width: 100%; height:18px;"></div>
        <div style="width: 100%; height:13px; border-bottom: 1px solid silver; text-align: center;">
          <span style="font-size: 15px; background-color: white; padding: 0 10px;">
            or
           </span>
        </div>
        <div style="padding:15px;">
          <h4>Sign up with a username</h4>
        </div>
        <div class="Sign_Form">
          <%= form_for(:rgluser, :url => {:controller => 'rglusers', :action => 'create'}, :html => {:class => "form-horizontal"}) do |f| %>
            <div class="form-group">
              <div class="col-sm-12"> <%= f.text_field :username, :placeholder =>'username',:class => 'form-control'%> </div>
            </div>
            <div class="form-group">
              <div class="col-sm-12">  <%= f.password_field :password, :placeholder => 'password',:class => 'form-control'%></div>
            </div>
            <div class="form-group">
              <div class="col-sm-12">  <%= f.password_field :password_confirmation, :placeholder => 'password confirmation',:class => 'form-control'%> </div>
            </div>
            <div class="form-group">
              <div class="col-sm-12">
                <%= f.submit "SIGN UP", :class => 'btn btn-block btn-success' %>
              </div>
            </div>
            <h3 style="text-align:center;font-size:100%;"> Already have an account? <%= link_to "Log in", welcome_parent_signin_path, :style => "color:#339900;" %></h3>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>