config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  
  post "welcome/login_attempt" => "welcome#login_attempt"
  resources :mentors
  get "mentors/detail/:id" => "mentors#detail", as: :mentors_detail

  get "welcome/forget_password" => "welcome#forget_password"
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get "administrators/new" => "administrators#new"
  get "administrators/create/:id" => "administrators#create", as: :administrators_create
  get "administrators/index" => "administrators#index"
  get "administrators/delete_one/:id" => "administrators#delete_one", as: :administrators_delete_one
  get "administrators/drop_table" => "administrators#drop_table"
  get "administrators/drop_all_mentor" => "administrators#drop_all_mentor"
  get "welcome/faq_open" => "welcome#faq_open"
  
  get "welcome/index" => "welcome#index"
  get "welcome/parent_signin" => "welcome#parent_signin"
  get "welcome/logout" => "welcome#logout"
  get "mentors_new" => "mentors#new"
  get "groupinvs/send_inv/:id" => "groupinvs#send_inv", as: :groupinvs_send_inv
  get "groupinvs/accept_inv_mentor/:id" => "groupinvs#accept_inv_mentor", as: :groupinvs_accept_inv_mentor
  get "groupinvs/accept_inv_group/:id" => "groupinvs#accept_inv_group", as: :groupinvs_accept_inv_group
  get "groupinvs/cancel_inv/:id" => "groupinvs#cancel_inv", as: :groupinvs_cancel_inv
  get "groupinvs/decline_inv/:id" => "groupinvs#decline_inv", as: :groupinvs_decline_inv
  
  get "parent" => "parent#index"
  get "parent/edit" => "parent#edit"
  put "parent" => "parent#update"
  get "parent/new" => "parent#new"
  post "parent/create" => "parent#create"
  
  get "mentor/quit_group/:id" => "mentors#quit_group", as: :mentor_quit_group
  get "invitation/group_send_inv_to_child/:id" =>"invitation#group_send_inv_to_child", as: :invitation_group_send_inv_to_child
  get "invitation/child_accept_group/:id" =>"invitation#child_accept_group", as: :invitation_child_accept_group
  get "invitation/cancel_inv/:id" => "invitation#cancel_inv", as: :invitation_cancel_inv
  get "invitation/decline_inv/:id" => "invitation#decline_inv", as: :invitation_decline_inv
  get "invitation/child_send_request_to_group/:id" => "invitation#child_send_request_to_group", as: :invitation_child_send_request_to_group
  
  get "invitation/group_accept_child/:id" => "invitation#group_accept_child", as: :invitation_group_accept_child
  resources :user
  resources :rglusers
  get 'fbuser/fb_login' => 'fbuser#fb_login', as: :fb_auth
  get 'casusers/cas_login' => 'casusers#cas_login', as: :cas_login
  get 'casusers/cas_logout' => 'casusers#cas_logout', as: :cas_logout
  resources :child
  get "child/detail/:id" => "child#detail", as: :child_detail
  get "child/message/:id" => "child#message", as: :child_message
  get "child/quit_group/:id" => "child#quit_group", as: :child_quit_group
  
  
  resources :group do
    collection do
      get 'index_for_parent'
    end
  end
    
  get 'group/:id/change' => 'group#change', as: :change_group
  get "group/set_complete/:id" => "group#set_complete", as: :group_set_complete
  get "group/set_need_mentor/:id" => "group#set_need_mentor", as: :group_set_need_mentor
  get "group/detail/:id" => "group#detail", as: :group_detail
  get "group/message/:id" => "group#message", as: :group_message
  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def login
    #Login Form
  end
  def login_attempt
    authorized_user = Rgluser.authenticate(welcome_params[:username],welcome_params[:login_password])
    if authorized_user
      session[:user_id] = authorized_user.user.id
      session[:expires_at] = Time.current + 2.hours
      authorized_user.user.update_columns(:last_login_time => Time.zone.now)
      flash[:success] = "Wow Welcome again, you logged in as #{authorized_user.role} "
      if authorized_user.user.role == 'Administrator'
        redirect_to administrators_index_path and return
      else 
        redirect_to parent_path and return
      end
    else
      flash[:warning] = "Invalid Username or Password"
      redirect_to welcome_parent_signin_path
    end
  end
  
  def logout
    if !User.whois(session).nil? && User.whois(session).role == "Mentor"
      redirect_to cas_logout_path
    else
      reset_session
      redirect_to welcome_index_path
    end
  end
  
  def index
    @user = User.whois(session)
    if !@user.nil?
      if @user.role=='Parent'
        if !@user.parent.nil?
          redirect_to parent_path and return
        else
          redirect_to parent_new_path and return
        end
      end
      if @user.role=='Mentor'
        if !@user.mentor.nil?
          redirect_to mentor_path(@user.mentor) and return
        else
          redirect_to new_mentor_path and return
        end
      end
    end

  end
  
  def forget_password
    
  end
  
  def faq_open
  end
  
  def send_password_email
    user = Parent.find_by_email(params[:email]).user
  end
  
  private 
  
  def welcome_params
      params.permit(:username, :login_password, :utf8, :authenticity_token, :commit)
  end
  
  def parent_signin
    
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/faq_open.html.erb
FAQ page

app/views/welcome/index.html.erb
<div class="row animated fadeIn">
  <div class="col-lg-12">
    <div class="intro-message">
      <h1>Howdy!</h1>
      <br/>
      <h1>This is Aggie-Buddy Connect!</h1>
      <br/>
      <h3>A platform for finding teammates and aggie mentors</h3>
      <hr class="intro-divider">
      <ul class="list-inline intro-social-buttons">
        <li>
          <%= link_to '<i class="fa fa-child fa-fw"></i><span class="network-name"> Parent</span>'.html_safe,  new_user_path(:role => 'Parent') , :class => 'btn btn-default btn-lg'%>
        </li>
        <li>
          <%= link_to image_tag('tamulogo.svg', :draggable=>"false", :style=>"width:30px; padding-right: 5px;padding-left: 5px;vertical-align: middle;")+'<span class="network-name"> Mentor</span>'.html_safe, cas_login_path , :class => 'btn btn-default btn-lg'%>
        </li>
      </ul>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
          $('body').addClass('background_image');
      });
</script>

app/views/welcome/parent_signin.html.erb
<!-- <% @page_title = "UserAuth | Login" -%> -->
<div class='row'>
  <div class="col-xs-12 col-sm-8 col-md-6 col-lg-4 col-sm-offset-2 col-md-offset-3 col-lg-offset-4">
    <div class="parent-login", style="padding-top:15%;">
      <div class="list-inline">
        <%= link_to '<i class="fa fa-facebook fa-fw"></i><span class="network-name"> Log in with facebook</span>'.html_safe, "/auth/facebook", id: "sign_in" , :class => 'btn btn-default btn-block', :style => "background-color:#3B5998;color:white;border-color:#2B4988;" %>
        <div style="width: 100%; height:18px;"></div>
        <div style="width: 100%; height:13px; border-bottom: 1px solid silver; text-align: center;">
          <span style="font-size: 15px; background-color: white; padding: 0 10px;">
            or
           </span>
        </div>
        <div class= "Sign_Form" style="padding:30px 16px 16px">
          <%= form_tag({:controller => 'welcome', :action => 'login_attempt'}, {:class => "form-horizontal"}) do %>
            <div class="form-group">
              <%= text_field_tag(:username, nil, placeholder: 'Username',class: 'form-control') %>
            </div>
            <div class="form-group">
              <%= password_field_tag( :login_password, nil, placeholder: 'Password',class: 'form-control' )%>
            </div>
            <div class="form-group">
              <%= submit_tag("LOG IN", class: 'btn btn-block btn-success') %>
            </div>
            <h3 style="text-align:center;font-size:100%;"><%= link_to "Forgot your password?", new_password_reset_path, :style => "color:#339900;" %></h3>
            <h3 style="text-align:center;font-size:100%;">Don't have an account? <%= link_to "Sign up", new_rgluser_path(:role => @role), :style => "color:#339900;" %></h3>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>