config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  
  post "welcome/login_attempt" => "welcome#login_attempt"
  resources :mentors
  get "mentors/detail/:id" => "mentors#detail", as: :mentors_detail

  get "welcome/forget_password" => "welcome#forget_password"
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get "administrators/new" => "administrators#new"
  get "administrators/create/:id" => "administrators#create", as: :administrators_create
  get "administrators/index" => "administrators#index"
  get "administrators/delete_one/:id" => "administrators#delete_one", as: :administrators_delete_one
  get "administrators/drop_table" => "administrators#drop_table"
  get "administrators/drop_all_mentor" => "administrators#drop_all_mentor"
  get "welcome/faq_open" => "welcome#faq_open"
  
  get "welcome/index" => "welcome#index"
  get "welcome/parent_signin" => "welcome#parent_signin"
  get "welcome/logout" => "welcome#logout"
  get "mentors_new" => "mentors#new"
  get "groupinvs/send_inv/:id" => "groupinvs#send_inv", as: :groupinvs_send_inv
  get "groupinvs/accept_inv_mentor/:id" => "groupinvs#accept_inv_mentor", as: :groupinvs_accept_inv_mentor
  get "groupinvs/accept_inv_group/:id" => "groupinvs#accept_inv_group", as: :groupinvs_accept_inv_group
  get "groupinvs/cancel_inv/:id" => "groupinvs#cancel_inv", as: :groupinvs_cancel_inv
  get "groupinvs/decline_inv/:id" => "groupinvs#decline_inv", as: :groupinvs_decline_inv
  
  get "parent" => "parent#index"
  get "parent/edit" => "parent#edit"
  put "parent" => "parent#update"
  get "parent/new" => "parent#new"
  post "parent/create" => "parent#create"
  
  get "mentor/quit_group/:id" => "mentors#quit_group", as: :mentor_quit_group
  get "invitation/group_send_inv_to_child/:id" =>"invitation#group_send_inv_to_child", as: :invitation_group_send_inv_to_child
  get "invitation/child_accept_group/:id" =>"invitation#child_accept_group", as: :invitation_child_accept_group
  get "invitation/cancel_inv/:id" => "invitation#cancel_inv", as: :invitation_cancel_inv
  get "invitation/decline_inv/:id" => "invitation#decline_inv", as: :invitation_decline_inv
  get "invitation/child_send_request_to_group/:id" => "invitation#child_send_request_to_group", as: :invitation_child_send_request_to_group
  
  get "invitation/group_accept_child/:id" => "invitation#group_accept_child", as: :invitation_group_accept_child
  resources :user
  resources :rglusers
  get 'fbuser/fb_login' => 'fbuser#fb_login', as: :fb_auth
  get 'casusers/cas_login' => 'casusers#cas_login', as: :cas_login
  get 'casusers/cas_logout' => 'casusers#cas_logout', as: :cas_logout
  resources :child
  get "child/detail/:id" => "child#detail", as: :child_detail
  get "child/message/:id" => "child#message", as: :child_message
  get "child/quit_group/:id" => "child#quit_group", as: :child_quit_group
  
  
  resources :group do
    collection do
      get 'index_for_parent'
    end
  end
    
  get 'group/:id/change' => 'group#change', as: :change_group
  get "group/set_complete/:id" => "group#set_complete", as: :group_set_complete
  get "group/set_need_mentor/:id" => "group#set_need_mentor", as: :group_set_need_mentor
  get "group/detail/:id" => "group#detail", as: :group_detail
  get "group/message/:id" => "group#message", as: :group_message
  root 'welcome#index'

end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
    belongs_to :user, class_name: "User", foreign_key: "user_id"
    has_many :groups
    serialize :competitions
    
    def name
        self.firstname+' '+self.lastname
    end
    
    def age 
        dob = self.date_of_birth
        now = Time.now.utc.to_date
        now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
    end
    
    EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
    validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
    validates :firstname, :presence => true
    validates :lastname, :presence => true
    validates :phone, :presence => true
    validates :gender, :presence => true
    validates :date_of_birth, :presence => true
    validate :is_valid_dob?
    validates :school, :presence => true
    validates :grade, :presence => true
    validates :time_slot, :presence => true
    validates :description, :length => { :in => 0..301}
    
    def self.all_grades
        %w(Freshman Sophomore Junior Senior Graduate Teacher)
    end
    
    private
    
    def is_valid_dob?
      errors.add(:dob, "Invalid date of birth") unless date_of_birth.past?
    end
    
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
   
   def new 
      @user=User.whois(session)
      redirect_to root_path and return if @user.nil? or @user.role != "Mentor" or !@user.mentor.nil?
      @mentor = Mentor.new
   end
   
  def create 
      @user=User.whois(session)
      redirect_to root_path and return if @user.nil? or @user.role != "Mentor"
      @mentor = Mentor.new(mentor_params)
      @mentor.user_id = session[:user_id]
      @mentor.visible = true
      if @mentor.save
        flash[:success] = "You have successfully filled your mentor file"
        redirect_to mentor_path(@mentor) and return
      else
        flash[:warning] = "Form is invalid"
        redirect_to new_mentor_path and return
      end
  end
    
  def index
    user = User.whois(session)
    if !session[:group_id].nil? 
      @group = Group.find_by_id(session[:group_id])
    else
      flash[:warning] = "Invalid user!"
      reset_session
      redirect_to welcome_index_path and return
    end
    if !user.nil? && user.role == "Parent"
      @mentors = Mentor.where(:visible => true)
    else
      flash[:warning] = "Invalid user!"
      reset_session
      redirect_to welcome_index_path and return
    end
  end
  
  def edit
      @mentor = check_user_and_return_mentor(session)
  end
  
  def show
      @mentor = check_user_and_return_mentor(session)
      @user = User.whois(session)
      redirect_to new_mentor_path and return if @mentor.nil?
      @id = @mentor.id
      @age = @mentor.age
      @groups = @mentor.groups
      @sinvs = Groupinv.where(:mentor_id => @mentor.id).where(:send_by_mentor => true)
      @rinvs = Groupinv.where(:mentor_id => @mentor.id).where(:send_by_mentor => false)
      
      @gn = @rinvs.where("updated_at > ?", @user[:last_login_time]).where(:status => 'Pending').count + @sinvs.where.not(:status => 'Pending').where("updated_at > ?", @user[:last_login_time]).count  
  end
  
  def update
      @mentor = check_user_and_return_mentor(session)
      if @mentor.update_attributes(mentor_params)
        flash[:success] = "Successfully updated"
        redirect_to mentor_path(@mentor) and return
      else
        flash[:warning] = "Invalid input form"
        render edit_mentor_path(@mentor) and return
      end
  end
  
  def destroy
    @mentor = check_user_and_return_mentor(session)
    if @mentor.destroy
      flash[:success] = "You have successfully deleted your profile. Now you should be on the login page"
      session[:user_id] = nil
      redirect_to welcome_index_path
    else 
      flash[:warning] = "Something's wrong. Please try again"
      redirect_to mentor_path(@mentor)
    end
  end
  
  def quit_group
    @mentor = check_user_and_return_mentor(session)
    GroupMailer.mentor_quit_notify(@mentor)
    @group = Group.find_by_id(params[:id])
    @group.mentor_id = nil
    @group.need_mentor = true
    @group.save!
    @mentor.update(:visible => true)
    redirect_to mentor_path(@mentor)
  end
  
  def detail
    @mentor = Mentor.find_by_id(params[:id])
    if @mentor.nil?
      redirect_to welcome_logout_path and return
    end
    @age = @mentor.age
    @user = @mentor.user
    if @mentor.groups.present?
      @group = @mentor.groups.first
      @time_slot = [@mentor.time_slot , @group.time_slot].join(',')
    else
      @time_slot = @mentor.time_slot
    end
  end
    
    
  private 
  
  def mentor_params
    params.require(:mentor).permit(:firstname, :password, :lastname, :phone, :email, :gender, :date_of_birth, :school, :grade, :time_slot, :competitions, :description, :user_id, :visible)
  end
  
  def check_user_and_return_mentor(session)
    user = User.whois(session)
    redirect_to root_path and return if user.nil?
    user.mentor
  end
  
end

app/views/mentors/detail.html.erb
<h1>Mentor Dashboard</h1>
ID: <%= @mentor.id %><br />
Name: <%= @mentor.name %><br/>
Phone: <%= @mentor.phone %><br />
Email: <%= @mentor.email %><br />
Age: <%= @age %><br />
Last Login at: <%= @user.last_login_time %><br />
Classification: <%= @mentor.grade %><br />
Department: <%= @mentor.school %><br />
Description: <%= @mentor.description %><br />
Time Available: 
<div class='time-board time-board-hover' value = '<%=@time_slot%>' ></div>
<%=link_to "Back" , mentors_path%>

app/views/mentors/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1 align="center" class="animated fadeInDown" style=color:#339900>Edit your profile</h1>
    <br/>
    <br/>
    <div class="Sign_Form">
      <%= form_for @mentor, :method => :put , :html => {:class => "form-horizontal"} do |f| %>
        <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2 col-lg-4 col-lg-offset-4">
          <div class="form-group">
            <label class="control-label">All fields are required unless marked as 'Optional'</label>
          </div>
          <div class="form-group">
            <label for="inputFirstname" class="control-label edit-font">Firstname</label>
            <%= f.text_field :firstname, :class => 'form-control'%>
          </div>
          <div class="form-group">
            <label for="inputLastname" class="control-label edit-font">Lastname</label>
            <%= f.text_field :lastname, :class => 'form-control'%>
          </div>
          <div class="form-group">
            <label for="inputGender" class="control-label edit-font">Gender</label>
            <%= f.select(:gender, ['Male' , 'Female'], {},{:class => 'form-control'})%>
          </div>
          <div class="form-group">
            <label for="inputPhone" class="control-label edit-font">Phone</label>
            <%= f.telephone_field :phone, :class => 'form-control'%>
          </div>
          <div class="form-group">
            <label for="inputPhone" class="control-label edit-font">Email</label>
            <%= f.email_field :email, :class => 'form-control'%>
          </div>
          <div class="form-group">
            <label for="inputDOB" class="control-label edit-font">Date of Birth</label>
            <%= f.date_field :date_of_birth, :class => 'form-control'%>
          </div>
          <div class="form-group">
            <label for="inputSchool" class="control-label edit-font">School</label>
            <%= f.text_field :school, :placeholder =>'School',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <label for="inputGrade" class="control-label edit-font">Grade</label>
            <%= f.select(:grade, ['Freshman' , 'Sophomore' , 'Junior' , 'Senior' , 'Graduate' , 'Teacher'], {},{:class => 'form-control'})%>
          </div>
          <div class="form-group">
            <label for="inputCompetitions" class="control-label edit-font">Competitions</label>
            <br/>
            <label class="radio-inline"><%= f.radio_button :competitions, 'FLL'%> FIRST LEGO League</label>
            <label class="radio-inline"><%= f.radio_button :competitions, 'Junior FLL'%> FIRST LEGO League Jr.</label>
          </div>
          <div class="form-group">
            <label for="inputDescription" class="control-label edit-font">Description(Optional):</label>
            <%= f.text_area :description, :class => 'form-control'%>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
          <div class="form-group">
            <label for="inputTimeslot" class="control-label edit-font">Time Available</label>
            <br/>
            <div class='time-board time-board-input time-board-hover' value='<%= @mentor.time_slot %>' inputname='mentor[time_slot]'></div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
          <div class="form-group">
            <br/>
            <br/>
            <%= f.submit "UPDATE",:class => 'btn btn-block btn-success'%>
            <%= link_to "CANCEL", mentor_path,:class => 'btn btn-block btn-default'%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/mentors/index.html.erb
<h1>Mentor List</h1>
<div class="table-responsive">
  <table class='table'>
    <tr>
      <th>ID</th>
      <th>Gender</th>
      <th>Age</th>
      <th>School</th>
      <th>Grade</th>
      <th>Time</th>
      <th>Competitions</th>
      <th>Description</th>
    </tr>
    <% @mentors.each do |mentor| %>
      <tr>
        <td><%= link_to mentor.id,  mentors_detail_path(mentor)%></td>
        <td><%= mentor.gender %></td>
        <td><%= mentor.age %></td>
        <td><%= mentor.school %></td>
        <td><%= mentor.grade %></td>
        <td><%= @group.time_compare(mentor.time_slot)%>
          <td><%= mentor.competitions %></td>
          <td><%= mentor.description %></td>
          <td><%= link_to "Send Invitation", groupinvs_send_inv_path(:id => @group.id, :mentor_id => mentor.id, :send_by_mentor => false) %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <%= link_to "Back", group_path(@group) %>

app/views/mentors/new.html.erb
<!-- <% @page_title = "Mentor | Signup" %> -->
<div class='row'>
  <div class="col-sm-12">
    <h1 align="center" class="animated fadeInDown" style=color:#339900>Create Account</h1>
    <br/>
    <div class="Sign_Form">
      <%= form_for(:mentor, :url => {:controller => 'mentors', :action => 'create'}, :html => {:class => "form-horizontal"}) do |f| %>
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
          <div class="form-group">
            <label class="control-label">All fields are required unless marked as 'Optional'</label>
          </div>
          <div class="form-group">
            <%= f.text_field :firstname, :placeholder =>'Firstname',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.text_field :lastname, :placeholder =>'Lastname',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.telephone_field :phone, :placeholder =>'Phone',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.email_field :email, :placeholder =>'Email',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.select(:gender, ['Male' , 'Female'], {prompt:"Gender"},{:class => 'form-control'})%>
          </div>
          <div class="form-group">
            <%= f.date_field :date_of_birth, :placeholder =>'Date of Birth',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.text_field :school, :placeholder =>'Department',:class => 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.select(:grade,['Freshman' , 'Sophomore' , 'Junior' , 'Senior' , 'Graduate' , 'Teacher'], {prompt: "Grade"},{:class => 'form-control'})%>
          </div>
          <div class="form-group">
            <label for="inputCompetitions" class="control-label">Competitions:</label>
            <br/>
            <label class="radio-inline"><%= f.radio_button :competitions, 'FLL'%> FIRST LEGO League</label>
            <label class="radio-inline"><%= f.radio_button :competitions, 'Junior FLL'%> FIRST LEGO League Jr.</label>
          </div>
          <div class="form-group">
            <label for="inputDescription" class="control-label">Description (Optional):</label>
            <br/>
            <%= f.text_area :description, :placeholder =>'More About Yourself',:class => 'form-control'%>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
          <div class="form-group">
            <label for="inputTimeslot" class="control-label">Time Available</label>
            <br/>
            <div class='time-board time-board-input time-board-hover' value='<%= @mentor.time_slot %>' inputname='mentor[time_slot]'></div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
          <div class="form-group">
            <%= f.submit "CREATE",:class => 'btn btn-block btn-success' %>
            <%= link_to "CANCEL", welcome_logout_path, :class =>'btn btn-block btn-default'%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% if @mentor.errors.any? %>
  <ul class="Signup_Errors">
    <% for message_error in @mentor.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
  </ul>
<% end %>
</div>

app/views/mentors/show.html.erb
<div class='row jumbotron'>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class = "col-xs-12 col-sm-12 col-md-6 col-lg-6">
      <h1 align="left" style="color:white;font-size:400%;" class="animated bounce"><b>Connect without limits</b></h1>
      <h2 align="left" style="color:white;font-size:150%;line-height:200%;">Aggies help future Aggies! Find groups who need tutoring and give a hand. Connection has never been this easy.</h2>
    </div>
  </div>
</div>
<div class='row'>
  <div id="content col-sm-12" style="overflow:hidden;">
    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3" style="background-color:#262626;margin-bottom:-99984px;padding-bottom:99999px;padding-top:15px;">
      <ul id="tabs" class="nav nav-pills nav-stacked" data-tabs="tabs">
        <li class="active"><a href="#account" data-toggle="tab">Account Overview</a></li>
        <li><a href="#group" data-toggle="tab">Your Group</a></li>
        <li><a href="#notification" data-toggle="tab">Notification<span class="badge pull-right"><%if !(@gn == 0) %><%= @gn %><% end %></span></a></li>
      </ul>
    </div>
    <div id="my-tab-content" class="tab-content">
      <div class="tab-pane fade in active" id="account">
        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 tab-pane-content">
          <div class='col-sm-12'>
            <h2>
              <div style="color:#6699FF">Account Overview</div>
            </h2>
            <hr class="overview-divider">
            <br/>
            <div class="table-responsive">
              <table class='table'>
                <tbody>
                  <tr>
                    <td><i class="fa fa-user fa-fw"></i> Name</td>
                    <td><%= @mentor.name %></td>
                  </tr>
                  <tr>
                    <td><i class="fa fa-phone fa-fw"></i> Phone</td>
                    <td><%= @mentor.phone %></td>
                  </tr>
                  <tr>
                    <td><i class="fa fa-envelope fa-fw"></i> Email</td>
                    <td><%= @mentor.email %></td>
                  </tr>
                  <tr>
                    <td><i class="fa fa-calendar fa-fw"></i> Age</td>
                    <td><%= @age %></td>
                  </tr>
                  <tr>
                    <td><i class="fa fa-list-ul fa-fw"></i> Description</td>
                    <td><%= @mentor.description %></td>
                  </tr>
                  <tr>
                    <td><i class="fa fa-clock-o fa-fw"></i> Time Slot</td>
                    <td></td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class='time-board time-board-hover' value = '<%=@mentor.time_slot%>' ></div>
            <br/>
            <br/>
            <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-6 col-lg-4 col-lg-offset-8">
            <p align="right"><%= link_to "Update Profile", edit_mentor_path(@mentor) , :class => 'btn btn-primary btn-block'%></p>
            <p align="right"> <%= link_to "Delete Account", mentor_path(@mentor),:class => 'btn btn-danger btn-block', data: {:confirm => 'Are you sure?',}, method: :delete%>
            </div>
          </div>
          </div>
        </div>
        
        
        <div class="tab-pane fade" id="group">
          <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 tab-pane-content">
            <div class="col-sm-12">
              <h2>
                <div style="color:#6699FF">Group</div>
              </h2>
              <hr class="overview-divider">
              <br/>
              <% if @groups.empty? %>
                <p align=center style="color:lightgrey;padding-top:25px;padding-bottom:25px;"><i class="fa fa-info-circle fa-lg" aria-hidden="true"></i><br/>
                  <b>Please find a group by clicking the button below.</b></p>
                <br/>
                <p><%= link_to "Browse Groups", group_index_path,:class => 'btn btn-primary col-xs-12 col-sm-12 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4' %></p>
              <% else %>
                <div class="table-responsive">
                  <table class='table'>
                    <thead>
                      <tr>
                        <th>Group</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @groups.each do |group| %>
                        <tr>
                          <td><%= link_to group.title, group_detail_path(:id => group.id, :mentor_id => @mentor.id) %></td>
                          <td><%= link_to "Quit the group", mentor_quit_group_path(group), :class => 'btn btn-default',  data: {:confirm => 'Are you sure?'} %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        
        
        <div class="tab-pane fade" id="notification">
          <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 tab-pane-content">
            <div class="col-sm-12">
              <h2>
                <div style="color:#6699FF">Group Notification</div>
              </h2>
              <hr class="overview-divider">
              <br/>
              <h2 style="font-size:150%;"><b>Request Received</b></h2>
              <% if @rinvs.empty? %>
                <p align=center style="color:lightgrey;padding-top:25px;padding-bottom:25px;"><i class="fa fa-info-circle fa-lg" aria-hidden="true"></i><br/>
                  <b>No requests Received.</b></p>
              <% else %>
                <div class="table-responsive">
                  <table class='table'>
                    <thead>
                      <tr>
                        <th>Sender</th>
                        <th>Status</th>
                        <th></th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @rinvs.each do |rinv| %>
                       <tr>
                       <td><%= link_to rinv.group_id, group_detail_path(:id => rinv.group.id, :mentor_id => @mentor.id)%></td>
                       <td><%= rinv.status %></td>
                      <% if rinv.status == 'Pending' %>
                       <td><%= link_to "Accept", groupinvs_accept_inv_mentor_path(rinv)%></td>
                       <td><%= link_to "Decline", groupinvs_decline_inv_path(rinv)%></td>
                     <% else %>
                         <td></td>
                        <td></td>
                         <% end %>
                        </tr>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
                <% end %>
              </div>
            
            
            
            <div class="col-sm-12">
              <h2 style="font-size:150%;"><b>Request Sent</b></h2>
              <% if @sinvs.empty? %>
                <p align=center style="color:lightgrey;padding-top:25px;padding-bottom:25px;"><i class="fa fa-info-circle fa-lg" aria-hidden="true"></i><br/>
                  <b>No Request Sent.</b></p>
              <% else %>
                <div class="table-responsive">
                  <table class='table'>
                    <thead>
                      <tr>
                        <th>Receiver</th>
                        <th>Status</th>
                        <th></th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @sinvs.each do |sinv| %>
                        <tr>
                          <td><%= link_to sinv.group_id, group_detail_path(:id => sinv.group.id, :mentor_id => @mentor.id) %></td>
                          <td><%= sinv.status %></td>
                          <% if sinv.status == "Pending" %>
                            <td><%= link_to "Cancel Invitation", groupinvs_cancel_inv_path(sinv)%></td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% session[:mentor_id] = @mentor.id %>
    <script>
      $(document).ready(function() {
                  $('body').addClass('parent_bg');
                  $('#tabs').tab();
              });
    </script>